In [357]:
import requests
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Sentiment Analysis

In [358]:
analyser = SentimentIntensityAnalyzer()

tweets = ['Fuck you nigger',"omg That's cool and amaizing","warui","bad","im selling",'Noooo',"stock is crashing!!","im so sad"]


negative_tweets = [
    "SUI is absolutely rekt today! Massive sell-off everywhere. #SUI #CryptoBloodbath",
    "What a disaster, SUI is dumping 20% in hours. Everyone panic selling! #SUI #CryptoCrash",
    "SUI plummeting hard, nothing is holding the price. Market chaos! #SUI #BearMarket",
    "This SUI crash is brutal, token bleeding out fast. Investors are terrified. #SUI #CryptoRuin",
    "SUI completely wiped out its gains. Total panic and sell-off happening now. #SUI #CryptoDisaster"
]
sentiments = []
for t in negative_tweets:
    sentiments.append(analyser.polarity_scores(t)['compound'])

sentiments

sum_sentiments = sum(sentiments)
len_sentiments = len(sentiments)

avg_sentiment = sum_sentiments/len_sentiments
print(avg_sentiment)

# Learning Point 

# Use List Comprehension
# sentiments = [ analyser.polarity_scores(t) for t in tweets ]
# sentiment

# analyser.polarity_scores('str') returns dict of feelings

# sum( np object )
# len( np object )

-0.54474

# Question 
How accurate is :
vaderSentiment.vaderSentiment SentimentIntensityAnalyzer

# Adoption of Coin Analysis

1.Adoption Proxy, that is the Binance Trading Volume 

any better ?

In [359]:
url = "https://api.binance.com/api/v3/klines"

params = {"symbol":"SUIUSDT",
          "interval" : "1d",
          "limit":1000,
          }

data = requests.get(url,params=params).json()

df = pd.DataFrame(data, columns=["time","open","high","low","close","volume",
                                 "close_time","qav","num_trades","taker_base_vol","taker_quote_vol","ignore"])
df

,time,open,high,low,close,volume,close_time,qav,num_trades,taker_base_vol,taker_quote_vol,ignore
0,1683072000000,0.10000000,2.00000000,0.10000000,1.40160000,446598493.40000000,1683158399999,612058253.94762000,1373630,218624854.30000000,299706207.11340000,0
1,1683158400000,1.40160000,1.49900000,1.29610000,1.33030000,160696442.60000000,1683244799999,222749446.27959000,521234,79893265.00000000,110918580.48925000,0
2,1683244800000,1.33030000,1.38000000,1.26000000,1.30640000,109103877.30000000,1683331199999,143184245.00059000,365619,53340993.40000000,70078469.45008000,0
3,1683331200000,1.30670000,1.37520000,1.27000000,1.32970000,84666618.70000000,1683417599999,112234146.54603000,290086,41223624.70000000,54723846.02755000,0
4,1683417600000,1.32990000,1.34690000,1.22000000,1.24310000,41904640.00000000,1683503999999,54269793.88247000,149622,17691131.70000000,22943394.37747000,0
...,...,...,...,...,...,...,...,...,...,...,...,...
836,1755302400000,3.71090000,3.78100000,3.66770000,3.77340000,19862546.80000000,1755388799999,74172468.14101000,276587,9983903.30000000,37289672.46974000,0
837,1755388800000,3.77350000,3.89460000,3.71030000,3.76390000,31113271.10000000,1755475199999,118601787.86618000,325299,15756001.40000000,60075708.90336000,0
838,1755475200000,3.76390000,3.77600000,3.52020000,3.60270000,54671610.70000000,1755561599999,197380760.60170000,562020,26798747.10000000,96727732.60422000,0
839,1755561600000,3.60270000,3.67660000,3.41460000,3.42220000,46741629.50000000,1755647999999,164993017.65482000,564756,22731457.70000000,80274182.94454000,0
840,1755648000000,3.42200000,3.56080000,3.37980000,3.51960000,32989207.60000000,1755734399999,114636458.63441000,358965,16608853.30000000,57741744.37463000,0

2.Normalising Adoption Score

adoption score is based on :

latest trading volume as relative to max trading vol

In [360]:
df['volume']=df['volume'].astype(float)

volume_window = df['volume'].iloc[-10:-1]

last_vol =df['volume'].iloc[-2] # -2 as yesterday's vol is used to avoid changes
max_vol = df['volume'].max()

adoption_score = last_vol/max_vol
adoption_score

volume_window

831    57743503.3
832    56867511.9
833    78552689.6
834    99844540.7
835    54547471.3
836    19862546.8
837    31113271.1
838    54671610.7
839    46741629.5
Name: volume, dtype: float64

# Forming the Indicator

indicator = w1*avg_sentiment + w2*adoption_score

In [361]:
print(f"Average Sentiment : {avg_sentiment}")
print(f"Adoption Score : {adoption_score}")

indicator = 0.6*avg_sentiment + 0.4*adoption_score
print(f"Indicator's Value : {indicator}")

Average Sentiment : -0.54474
Adoption Score : 0.10466141330695318
Indicator's Value : -0.2849794346772187